services:
  - type: web
    name: django-event-manager
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn event_management.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.13.0
